"""EXAM

Revision ID: 43175a336131
Revises: d73904ea9ac6
Create Date: 2024-06-12 16:55:05.233844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43175a336131'
down_revision = 'd73904ea9ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_genres', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_genres_book_id_books', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_genres_book_id_books'), 'books', ['book_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_book_id_books', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_book_id_books'), 'books', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_reviews_book_id_books', 'books', ['book_id'], ['id'])

    with op.batch_alter_table('books_genres', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_genres_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_genres_book_id_books', 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###
